GET http://localhost:3030/api/congratulate

### 
POST http://localhost:3030/api/congratulate
content-type: application/json

{
    "author": "tung2",
    "note": "Selamat"
}

### 
PUT http://localhost:3030/api/congratulate
content-type: application/json

{
    "id": 3,
    "from": "Tung",
    "message": "message from aku"
}


###
# ADMIN #
GET http://localhost:3030/api/admin/congratulate?page=1&limit=5
content-type: application/json

###
PUT http://localhost:3030/api/admin/congratulate/4
content-type: application/json

{
    "active": true
}