GET http://localhost:3030/api/visitor

### 
POST http://localhost:3030/api/visitor
content-type: application/json

{
    "username": "febri-tung"
}

###
# ADMIN #
GET http://localhost:3030/api/admin/visitor
